import StructuredData from '@/components/structured-data';
import {siteSchema} from '@/lib/seo.mjs';
import Link from 'next/link';
import {data,brand,config,guideUrl,topicUrl,metadata as pageMetadata} from '@/lib/content';
import {Photo,SectionTitle,StoryCard,CityCard} from '@/components/editorial';
export const metadata=pageMetadata('Sidestreet — City life & global culture','Independent city guides, local food, culture and discoveries from Bangkok to the world.',undefined,'/');
export default function Home(){
 const story=id=>data.stories.find(s=>s.id===id);const lead=story('g-neighbourhoods'),hotel=story('bkk-hotels'),escape=story('lis-views');
 const picks=['bkk-street-food','tyo-listening','bkk-rooftops','ygn-teashops'].map(story);const markets=['bkk-night-markets','cnx-markets','mex-markets'].map(story);
 return <main id="main"><StructuredData value={siteSchema(config.siteUrl,brand,config.publisherName)}/><section className="cover container" id="cover-story"><div className="issue-stamp"><div><strong>THE CITY EDIT</strong><span className="mono">GLOBAL CULTURE ISSUE<br/>{data.cities.length} CITIES / {data.stories.length} FIELD GUIDES</span></div><span className="mono">LOCAL STORIES. GLOBAL CURIOSITY.<br/><b>FIELD DISPATCH: {brand.toUpperCase()}</b></span></div><div className="cover-grid"><article className="cover-lead"><Photo id={lead.img} alt="Historic street life in Bangkok’s Talat Noi neighbourhood" priority/><div className="hero-gradient"/><div className="cover-labels mono"><span>THE COVER STORY № 01</span><span>WORLDWIDE / LOCAL LIFE</span></div><div className="cover-copy"><span className="eyebrow gold">AN INDEPENDENT WORLDWIDE GUIDE</span><h1>TAKE THE<br/><span className="stroke-text">SIDE</span><br/>STREETS.</h1><p>“Find the neighbourhoods where local life, independent culture and the city’s best food come together.”</p><div className="cover-actions"><Link className="button" href={guideUrl(lead)}>DISCOVER THE NEIGHBOURHOODS ↗</Link><span className="mono">{lead.mins} MIN READ / WORLD DISPATCH</span></div></div></article><div className="cover-secondary"><article className="hotel-feature"><div className="small-stamp mono"><span>HOTEL MONOGRAPH</span><span>BANGKOK / RIVERSIDE</span></div><Photo id={hotel.img} alt="Mandarin Oriental Bangkok by the Chao Phraya River" priority/><h2>Beautiful stays.<br/>A different view of the city.</h2><p><span className="drop-cap">F</span>rom historic riverside addresses to contemporary escapes, find a place to stay that makes the journey part of the story.</p><div className="card-bottom mono"><span>THE BANGKOK HOTEL EDIT</span><Link href={guideUrl(hotel)}>READ THE GUIDE ↗</Link></div></article><article className="escape-feature"><Photo id={escape.img} alt="Lisbon rooftops and views"/><div><span className="eyebrow gold">THE SLOW ESCAPE</span><h3>Seven hills.<br/>A thousand perspectives.</h3><p>Trams, rooftops and the best views in Lisbon.</p><Link className="mono gold" href={guideUrl(escape)}>READ DISPATCH ↗</Link></div></article></div></div></section>
 <section className="container editorial-section" id="inspiration-rankings"><SectionTitle eyebrow="LOCAL LIFE / THE EDITORIAL INDEX" title="A DIFFERENT SIDE OF THE CITY" href={topicUrl('things')}/><div className="story-grid four">{picks.map((s,i)=><StoryCard key={s.id} story={s} index={i}/>)}</div></section>
 <section className="market-section" id="market-portal"><div className="container"><SectionTitle eyebrow="AUTHENTIC CULINARY COMMONS / AFTER DARK" title="MEET YOU AT THE MARKET" href={topicUrl('food')} label="Explore food & drink"/><p className="section-intro">“No white tablecloths. Just the city’s best street fare, independent makers, and the places everyone comes together.”</p><div className="story-grid three">{markets.map((s,i)=><StoryCard key={s.id} story={s} index={i}/>)}</div><div className="market-foot mono">BANGKOK · CHIANG MAI · MEXICO CITY <Link href="/whats-on">WHAT’S ON WORLDWIDE ↗</Link></div></div></section>
 <section className="container editorial-section"><SectionTitle eyebrow="CITY RHYTHMS / CULTURE & CONNECTION" title="SOUND & SLOW JOURNEYS"/><div className="culture-grid"><article className="culture-feature"><Photo id={story('tyo-listening').img} alt="Tokyo listening bar"/><div><span className="eyebrow">SONIC FIELD NOTES / TOKYO</span><h2>LISTEN<br/><span className="stroke-text-dark">CLOSER.</span></h2><blockquote>“{story('tyo-listening').dek}”</blockquote><Link className="mono text-link" href={guideUrl(story('tyo-listening'))}>OPEN THE LISTENING GUIDE ↗</Link></div></article><article className="culture-feature travel-feature"><Photo id={story('g-trains').img} alt="Rail journey through Southeast Asia"/><div><span className="eyebrow gold">THE LONG WAY HOME</span><h2>THE ART OF<br/>SLOW TRAVEL.</h2><blockquote>“{story('g-trains').dek}”</blockquote><Link className="mono gold" href={guideUrl(story('g-trains'))}>EXPLORE RAIL JOURNEYS ↗</Link></div></article></div></section>
 <section className="container editorial-section" id="new-guides"><SectionTitle eyebrow="THE LATEST FIELD NOTES" title="FRESH DISPATCHES" href={topicUrl('things')} label="More things to do"/><div className="story-grid three">{data.stories.slice(-6).reverse().map(s=><StoryCard key={s.id} story={s}/>)}</div></section>
 <section className="container editorial-section" id="city-atlas"><SectionTitle eyebrow="GEOGRAPHIC FIELD GUIDES" title="GLOBAL CITY ATLAS" href="/cities" label={`All ${data.cities.length} destinations`}/><div className="city-grid">{['bkk','ygn',...data.cities.slice(-6).map(c=>c.id)].map(id=><CityCard key={id} city={data.cities.find(c=>c.id===id)}/>)}</div></section>
 <section className="container service-home"><span className="eyebrow">THE BEST FOR YOUR TRIP</span><h2>FIND THE SERVICE YOU NEED</h2><p>Transport, tours, meals, stays, mobile data and useful shops — choose by destination and visitor need.</p><Link className="button" href="/services">EXPLORE TRAVEL SERVICES ↗</Link><Link className="text-link" href="/updates">FOLLOW CITY UPDATES ↗</Link></section>
 <section className="guide-invite container"><span className="eyebrow">THE NEXT CHAPTER IS YOURS</span><h2>WHERE WILL YOU<br/>TAKE THE SIDE STREET?</h2><p>Choose a city. Find a local favourite. Make a different kind of plan.</p><Link href="/cities" className="button">OPEN THE CITY ATLAS ↗</Link></section></main>
}
