import Link from 'next/link';
import {data,photoFor,cityFor,cityUrl,guideUrl,topicUrl} from '@/lib/content';
import {eventDate,isUpcoming} from '@/lib/events.mjs';
export function Photo({id,alt='',className='',priority=false,credit=false,note='',sizes='(max-width: 760px) calc(100vw - 40px), (max-width: 1520px) calc(100vw - 344px), 1176px'}){const p=photoFor(id);if(!p)return null;return <figure className={className}><img src={p.src} srcSet={p.variants?.length?[...p.variants,{src:p.src,w:p.w}].map(v=>`${v.src} ${v.w}w`).join(', '):undefined} sizes={p.variants?.length?sizes:undefined} decoding="async" alt={p.alt||alt} width={p.w} height={p.h} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'}/>{credit&&<figcaption>{p.kind==='illustration'?'Illustration: ':'Photo: '}<a href={p.page} target="_blank" rel="noopener noreferrer">{p.by}</a> · {p.licUrl?<a href={p.licUrl} target="_blank" rel="noopener noreferrer">{p.lic}</a>:p.lic}{p.kind!=='illustration'&&' · Resized and cropped'}{(note||p.note)&&<span className="photo-note"> {note||p.note}</span>}</figcaption>}</figure>}
export function SectionTitle({eyebrow,title,href,label='Explore all'}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{href&&<Link href={href} className="mono text-link">{label} ↗</Link>}</div>}
export function StoryCard({story,index}){return <article className="story-card">{index!==undefined&&<div className="card-index mono">FIELD NOTE {String(index+1).padStart(2,'0')} <span>{cityFor(story.city)?.code||'WORLD'}</span></div>}<Link href={guideUrl(story)}><Photo id={story.img} alt={story.title} sizes="(max-width: 760px) calc(100vw - 40px), (max-width: 1100px) calc((100vw - 90px) / 2), (max-width: 1520px) calc((100vw - 116px) / 3), 468px"/><span className="eyebrow">{data.categories[story.cat]} / {cityFor(story.city)?.name||'Worldwide'}</span><h3>{story.title}</h3><p>{story.dek}</p><div className="card-bottom mono"><span>{story.mins} MIN READ</span><span>READ ↗</span></div></Link></article>}
export function CityCard({city}){return <article className="city-card"><Link href={cityUrl(city)}><div className="city-photo"><Photo id={city.img} alt={city.name} sizes="(max-width: 760px) calc(100vw - 40px), (max-width: 1100px) calc((100vw - 90px) / 2), (max-width: 1520px) calc((100vw - 114px) / 3), 468px"/><span className="coordinates mono">{Math.abs(city.lat).toFixed(4)}° {city.lat>=0?'N':'S'}, {Math.abs(city.lng).toFixed(4)}° {city.lng>=0?'E':'W'}</span></div><span className="eyebrow">{city.country}</span><h3>{city.name}</h3><p>{city.line}</p><div className="card-bottom mono"><span>{data.places.filter(p=>p.city===city.id).length} PLACES</span><span>EXPLORE DOSSIER ↗</span></div></Link></article>}
export function Places({places}){return <div className="place-list">{places.map(p=><article className="place-row" key={p.id} id={p.id} data-place-kind={p.kind}><div><span className="eyebrow">{data.kinds[p.kind]} · {p.area}</span><h3>{p.name}</h3><p>{p.blurb}</p>{(p.hours||p.price)&&<p className="facts-line">{p.hours&&<span>Hours: {p.hours}</span>}{p.price&&<span>Cost: {p.price}</span>}</p>}<div className="source-links">{p.verify&&<span className="warning">Check before you go</span>}{p.url&&<a href={p.url} target="_blank" rel="noopener noreferrer">Website ↗</a>}{(p.src||[]).map(id=>data.sources[id]&&<a key={id} href={data.sources[id].url} target="_blank" rel="noopener noreferrer">{data.sources[id].name} ↗</a>)}</div></div><Photo id={p.img} alt={p.name} credit note={p.imageNote} sizes="(max-width: 760px) calc(100vw - 40px), (max-width: 1520px) 40vw, 582px"/></article>)}</div>}
export function Events({events}){const active=events.filter(e=>isUpcoming(e,data.cities)).sort((a,b)=>a.date.localeCompare(b.date));return active.length?<div className="event-list">{active.map(e=><article key={e.id} className="event-row"><div className="event-date mono">{eventDate(e)}</div><div><span className="eyebrow">{e.cat} · {cityFor(e.city)?.name}</span><h3>{e.title}</h3><p>{e.blurb}</p><span className="mono muted">{e.where}{e.time?' · '+e.time:''}</span><div className="source-links">{e.url&&<a href={e.url} target="_blank" rel="noopener noreferrer">Website ↗</a>}{(e.src||[]).map(id=>data.sources[id]&&<a href={data.sources[id].url} key={id} target="_blank" rel="noopener noreferrer">Source ↗</a>)}<Link href={cityUrl(cityFor(e.city))}>City guide ↗</Link></div></div></article>)}</div>:<p className="empty">No confirmed upcoming dates are listed right now. Explore our city guides for places to visit.</p>}
export function TopicLinks(){return <div className="topic-links">{Object.entries(data.categories).map(([id,name])=><Link key={id} href={topicUrl(id)}>{name} ↗</Link>)}</div>}
