'use client';
import {useState} from 'react';
import Link from 'next/link';
export default function ServiceDirectory({cities,categories,listings,sponsored,sources,initialCity='',initialCategory='',guides=[]}){
 const [city,setCity]=useState(initialCity),[category,setCategory]=useState(initialCategory),[search,setSearch]=useState('');
 const matches=p=>(!city||p.city===city)&&(!category||p.category===category)&&(!search||[p.name,p.blurb,p.description,p.bestFor,p.area].join(' ').toLowerCase().includes(search.toLowerCase()));
 const independent=listings.filter(matches),paid=sponsored.filter(matches);
 const matchingGuides=guides.filter(g=>(!city||g.city===city)&&(!category||g.category===category));
 const chosen=categories.find(c=>c.id===category);
 return <div className="service-directory">{matchingGuides.length>0&&<section className="editorial-section service-guides"><span className="eyebrow">THE SHOP & SERVICE EDIT</span><h2>READ THE COMPARISON GUIDES</h2><p>Named businesses, practical comparisons and the questions to ask before booking.</p><div className="story-grid three">{matchingGuides.map(g=>g.card)}</div></section>}<div className="service-controls"><label>Destination<select value={city} onChange={e=>setCity(e.target.value)}><option value="">All destinations</option>{cities.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Find a service<input type="search" placeholder="Try cooking, hotel or a business name" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="filter-chips" role="group" aria-label="Service categories"><button aria-pressed={!category} onClick={()=>setCategory('')}>All services</button>{categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div>{chosen&&<div className="service-category-note"><h2>{chosen.name}</h2><p>{chosen.description}</p><p>{chosen.check}</p></div>}
 {paid.length>0&&<section className="sponsored-services"><h2>Sponsored services</h2><p>Paid placements. Payment does not establish an editorial ranking.</p><div className="services-grid">{paid.map(p=><article className="service-card sponsored" key={p.id}><span className="sponsor-label">Sponsored · Paid placement</span><h3>{p.name}</h3><p><strong>Best for:</strong> {p.bestFor}</p><p>{p.description}</p><a className="text-link" href={p.url} rel="sponsored noopener noreferrer" target="_blank">Visit advertiser ↗</a></article>)}</div></section>}
 <h2 className="service-results-heading">Independent directory <span>({independent.length})</span></h2><p className="muted">“Best for” describes a visitor need, not a scored award. These listings are not paid placements.</p>
 {!independent.length&&<div className="service-empty"><p>No independent listing matches these filters yet. Try another category or destination.</p><button onClick={()=>{setCity('');setCategory('');setSearch('');}}>Reset filters</button></div>}
 <div className="services-grid">{independent.map(p=>{const c=cities.find(c=>c.id===p.city),cat=categories.find(c=>c.id===p.category);return <article className="service-card" key={p.id}><span className="eyebrow">{cat?.name} / {c?.name}</span><h3>{p.name}</h3><p className="service-fit"><strong>Best for:</strong> {p.bestFor}</p><p>{p.blurb}</p><p className="muted">{p.area}</p>{p.url&&<a className="text-link" href={p.url} target="_blank" rel="noopener noreferrer">Official information / booking ↗</a>}<Link className="text-link" href={'/city/'+c?.slug+'#'+p.id}>City listing ↗</Link>{p.guideSlug&&<Link className="text-link" href={'/guides/'+p.guideSlug}>Read our comparison guide ↗</Link>}<details><summary>Research & booking checks</summary><p>{cat?.check}</p><p>No firsthand inspection or guaranteed availability is claimed.</p>{p.src?.map(id=>sources[id]&&<a className="source-link" key={id} href={sources[id].url} target="_blank" rel="noopener noreferrer">{sources[id].name} ↗</a>)}</details></article>;})}</div>
 </div>;
}
