import CityFollow from '@/components/city-follow';
import {updateFeed} from '@/lib/update-feed';
import Link from 'next/link';
import Search from './search';
import {brand,data,config,cityUrl,guideUrl,topicUrl} from '@/lib/content';
export function Header(){
 const entries=[...data.cities.map(c=>({title:c.name,label:'City · '+c.country,href:cityUrl(c),keywords:c.code+' '+c.country})),...data.stories.map(s=>({title:s.title,label:data.categories[s.cat],href:guideUrl(s),keywords:s.dek})),...data.places.map(p=>({title:p.name,label:data.kinds[p.kind],href:cityUrl(data.cities.find(c=>c.id===p.city))+'#'+p.id,keywords:p.blurb+' '+p.area}))];
 return <header className="site-header" id="top"><a className="skip-link" href="#main">Skip to content</a><div className="dispatch-bar"><span>GLOBAL DISPATCH: BANGKOK · YANGON · TOKYO · LONDON · NEW YORK</span><Link href="/cities">WORLDWIDE EDITION ↗</Link></div><div className="masthead container"><Link href="/" className="wordmark">{brand}<span>CITY LIFE & GLOBAL CULTURE</span></Link><Search entries={entries}/><CityFollow compact cities={data.cities.map(({id,name,country})=>({id,name,country}))} feed={updateFeed()}/><Link className="atlas-link" href="/cities">CITY ATLAS <span>↘</span></Link></div><nav className="section-nav container" aria-label="Main navigation"><Link href="/">01 COVER FEATURE</Link><Link href={topicUrl('things')}>02 THINGS TO DO</Link><Link href={topicUrl('food')}>03 FOOD & DRINK</Link><Link href={topicUrl('travel')}>04 TRAVEL</Link><Link href={topicUrl('music')}>05 SOUND & CULTURE</Link><Link href="/whats-on">06 WHAT’S ON</Link><Link href={topicUrl('news')}>07 CITY NEWS</Link><Link href="/services">08 TRAVEL SERVICES</Link></nav><div className="ticker"><div>★ TAKE THE SIDE STREET /// INDEPENDENT FOOD, LOCAL CULTURE & UNEXPECTED DISCOVERIES /// {data.cities.length} CITIES · {data.stories.length} FIELD GUIDES /// BANGKOK TO THE WORLD /// ★ TAKE THE SIDE STREET /// INDEPENDENT FOOD, LOCAL CULTURE & UNEXPECTED DISCOVERIES ///</div></div></header>
}
export function Footer(){return <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Link href="/" className="wordmark">{brand}</Link><p>A city guide for the curious. Take the back streets, find the local favourites, and see a different side of the world.</p><span className="mono">BANGKOK · YANGON · TOKYO · LONDON</span></div><div><h3>EDITORIAL SECTORS</h3>{Object.entries(data.categories).map(([id,name])=><Link key={id} href={topicUrl(id)}>{name}</Link>)}</div><div><h3>ASIA & PACIFIC</h3>{data.cities.filter(c=>['Asia','South Pacific'].includes(c.region)).slice(0,6).map(c=><Link href={cityUrl(c)} key={c.id}>{c.name}</Link>)}</div><div><h3>GLOBAL BUREAU</h3>{data.cities.filter(c=>!['Asia','South Pacific'].includes(c.region)).slice(0,6).map(c=><Link href={cityUrl(c)} key={c.id}>{c.name}</Link>)}</div><div><h3>ABOUT THE GUIDE</h3><Link href="/about">About & sources</Link><Link href="/editorial-policy">Editorial policy</Link><Link href="/advertising-policy">Advertising policy</Link><Link href="/updates">Follow city updates</Link><Link href="/services">Travel services</Link><Link href="/advertise">Advertise your business</Link><Link href="/contact">Contact</Link><Link href="/credits">Photo credits</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of use</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {config.publisherName||brand}</span><span>INDEPENDENT CITY DISCOVERIES</span><a href="#top">BACK TO TOP ↑</a></div></footer>}
