import CityFollow from '@/components/city-follow';
import CityServices from '@/components/city-services';
import {updateFeed} from '@/lib/update-feed';
import StructuredData from '@/components/structured-data';
import {collectionSchema,breadcrumbSchema} from '@/lib/seo.mjs';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {data,config,metadata} from '@/lib/content';
import {Photo,StoryCard,Places,Events,SectionTitle} from '@/components/editorial';
import PlaceFilter from '@/components/place-filter';
export const dynamic='force-dynamic';
export async function generateMetadata({params}){const {slug}=await params;const c=data.cities.find(c=>c.slug===slug);return c?metadata(c.name+' city guide',c.line,c.img,'/city/'+c.slug):{};}
export default async function City({params}){const {slug}=await params;const c=data.cities.find(c=>c.slug===slug);if(!c)notFound();const places=data.places.filter(p=>p.city===c.id);const stories=data.stories.filter(s=>s.city===c.id);const kinds=Object.entries(data.kinds).filter(([id])=>places.some(p=>p.kind===id)).map(([id,name])=>({id,name}));return <main id="main" className="container directory"><StructuredData value={collectionSchema(config.siteUrl,c.name+' city guide','/city/'+c.slug,stories.map(s=>[s.title,'/guides/'+s.slug]))}/><StructuredData value={breadcrumbSchema(config.siteUrl,[['Home','/'],[c.name+' city guide','/city/'+c.slug]])}/><div className="breadcrumbs"><Link href="/cities">City atlas</Link> / {c.name}</div><section className="city-banner"><div><span className="eyebrow">{c.country} / {c.region}</span><h1>{c.name}</h1><p>{c.line}</p><dl className="city-facts"><dt>Currency</dt><dd>{c.money}</dd><dt>Time zone</dt><dd>{c.utc}</dd><dt>Airports</dt><dd>{c.airport}</dd><dt>Getting around</dt><dd>{c.transit}</dd></dl></div><Photo id={c.img} alt={c.name} priority credit/></section><CityFollow cityId={c.id} cities={data.cities.map(({id,name,country})=>({id,name,country}))} feed={updateFeed()}/><CityServices city={c}/>{c.advisory&&<p className="notice">{c.advisory.text} <a href={c.advisory.url} target="_blank" rel="noopener noreferrer">Read the advice ↗</a></p>}<section className="editorial-section"><SectionTitle eyebrow="THE LOCAL CALENDAR" title={'WHAT’S ON IN '+c.name.toUpperCase()}/><Events events={data.events.filter(e=>e.city===c.id)}/></section>{stories.length>0&&<section className="editorial-section"><SectionTitle eyebrow="FIELD NOTES" title={c.name.toUpperCase()+' GUIDES'}/><div className="story-grid three">{stories.map(s=><StoryCard key={s.id} story={s}/>)}</div></section>}<section className="editorial-section"><SectionTitle eyebrow="PLACES & LOCAL FAVOURITES" title={'EXPLORE '+c.name.toUpperCase()}/><PlaceFilter kinds={kinds}><Places places={places}/></PlaceFilter><p className="muted">Hours and prices may change. Confirm with the venue before a special trip.</p></section></main>}
